Repository dyvenia/timeflow, pull requests merged in 2022-07, with the labels that each got.

#399 |Components| Dropdown component reset
  applications/timeflow/pages/timelogs.py
  uiflow/components/input.py
Labels: bug

#400 |Pages||All| Page components reload on enter
  applications/timeflow/index.py
  applications/timeflow/pages/capacities.py
  applications/timeflow/pages/clients.py
  applications/timeflow/pages/demands.py
  applications/timeflow/pages/epic_areas.py
  applications/timeflow/pages/epics.py
  applications/timeflow/pages/forecasts.py
  applications/timeflow/pages/rates.py
  applications/timeflow/pages/roles.py
  applications/timeflow/pages/sponsors.py
  applications/timeflow/pages/teams.py
  applications/timeflow/pages/timelogs.py
  applications/timeflow/pages/users.py
Labels: bug

#404 Make logo clickable
  uiflow/components/header.py
Labels: enhancement

#410 🐛 |Pages||Users| added github username to newly posted user's name
  appflow/views/login_github.py
Labels: bug

#406 Remove team_id from Capacities model
  .gitignore
  applications/timeflow/data/capacities.py
  applications/timeflow/pages/capacities.py
  backend/api/capacity.py
  backend/models/capacity.py
  backend/tests/test_capacity_api.py
  backend/tests/test_demand_api.py
  migrations/version_archive/b85bfd91b12d_add_start_date_column_to_epicarea_model.py
  migrations/versions/1340e2e5f418_remove_team_id_column_from_capacities_.py
Labels: enhancement, migration needed

#411 [QuickFic] Update sql sample for capacities
  backend/tests/sample.sql
Labels: bug

#413 ✨ |Pages||Capacities| Capacities eabled for users
  applications/timeflow/data/capacities.py
  applications/timeflow/data/forecasts.py
  applications/timeflow/data/users.py
  applications/timeflow/index.py
  applications/timeflow/pages/capacities.py
  applications/timeflow/pages/clients.py
  applications/timeflow/pages/forecasts.py
  applications/timeflow/pages/utils.py
  backend/api/capacity.py
  backend/api/forecast.py
  backend/api/user.py
  uiflow/components/input.py
  uiflow/components/table.py
Labels: enhancement

#417 Create column business_day for calendar
  backend/models/calendar.py
  migrations/versions/bd25fbcfe742_add_business_day_column.py
Labels: enhancement, migration needed

#419 Update changelog with latest PRs
  CHANGELOG.md
Labels: documentation

#421 Make user dropdown in `Capacities` ascend alphabetically
  applications/timeflow/data/users.py
Labels: enhancement

#423 Updated calendar.csv with prod calendar table changes
  backend/calendar.csv
  backend/main.py
Labels: enhancement

#428 ✨ |Pages||Capacities| Add business days feature
  CHANGELOG.md
  applications/timeflow/data/calendar.py
  applications/timeflow/pages/capacities.py
  backend/api/calendar.py
  backend/main.py
Labels: enhancement

#430 |Pages||Foracasts||Capacities| Capacities styling + forecast validator
  CHANGELOG.md
  applications/timeflow/data/capacities.py
  applications/timeflow/pages/capacities.py
  applications/timeflow/pages/timelogs.py
  backend/api/capacity.py
  backend/api/forecast.py
  uiflow/components/layout.py
Labels: bug, enhancement

#433 Last user not showing up in user dropdown
  applications/timeflow/data/users.py
Labels: bug
