Repository dyvenia/timeflow, pull requests merged in 2022-05, with the labels that each got.

#274 Remove epic areas constraint which forces epic area names to be unique
  applications/timeflow/pages/epic_areas.py
  backend/api/epic_area.py
Labels: bug

#279 Fixed missing columns in transactional tables
  applications/timeflow/data/forecasts.py
  applications/timeflow/data/timelogs.py
  applications/timeflow/pages/timelogs.py
  backend/models/forecast.py
  backend/models/timelog.py
  backend/tests/sample.sql
Labels: bug

#287 Bug epic epic area
  applications/timeflow/data/epic_areas.py
  applications/timeflow/data/timelogs.py
  applications/timeflow/pages/timelogs.py
  backend/api/timelog.py
  uiflow/components/input.py
Labels: bug

#292 Bug epic epic area 2.0
  applications/timeflow/data/epic_areas.py
  applications/timeflow/data/timelogs.py
  applications/timeflow/pages/timelogs.py
  backend/api/timelog.py
  uiflow/components/input.py
Labels: enhancement

#293 ✨ added forecasts table on enter
  applications/timeflow/data/forecasts.py
  applications/timeflow/pages/forecasts.py
  backend/api/forecast.py
Labels: enhancement

#294 ✨ added epics table on enter
  applications/timeflow/data/epics.py
  applications/timeflow/pages/epics.py
  backend/api/epic.py
Labels: enhancement

#296 ✨ validating timelog post with epic start date
  backend/api/timelog.py
Labels: enhancement

#300 Update activation/deactivation dropdowns for epics page
  applications/timeflow/data/epics.py
  applications/timeflow/pages/demands.py
  applications/timeflow/pages/epic_areas.py
  applications/timeflow/pages/epics.py
  applications/timeflow/pages/forecasts.py
  applications/timeflow/pages/timelogs.py
  backend/api/epic.py
Labels: enhancement

#299 Updated activ/deactiv dropdowns
  applications/timeflow/data/users.py
  applications/timeflow/pages/users.py
  backend/api/user.py
Labels: enhancement

#303 🐛[Quick Fix] Add is_event and set_is_event to timelog page component
  applications/timeflow/pages/timelogs.py
Labels: bug

#311 Update number of default rows in a table
  uiflow/components/table.py
Labels: enhancement

#310 Move Forecasts page to Admin Collapse #260
  applications/timeflow/index.py
Labels: enhancement

#312 #309 |Pages||Rates| Add rates table on enter
  applications/timeflow/data/rates.py
  applications/timeflow/pages/rates.py
  backend/api/rate.py
Labels: enhancement

#321 #307 |Pages||All| Full names only visible on frontend
  applications/timeflow/data/demands.py
  backend/api/demand.py
  backend/api/forecast.py
  backend/api/timelog.py
Labels: enhancement

#328 #327 |Rates| Add filter by client name
  applications/timeflow/data/rates.py
  applications/timeflow/pages/rates.py
  backend/api/rate.py
Labels: enhancement

#326 Admin collapse to no longer overlap Forecasts on hover
  uiflow/components/sidebar.py
Labels: bug

#325 #324 |Pages||All| Full names only visible on frontend (role names)
  applications/timeflow/data/capacities.py
  applications/timeflow/data/demands.py
  applications/timeflow/data/users.py
  backend/api/capacity.py
  backend/api/demand.py
  backend/api/forecast.py
  backend/api/timelog.py
  backend/api/user.py
Labels: enhancement

#323 |Pages||Timelogs| Added date_time picker for timelogs
  applications/timeflow/pages/timelogs.py
  backend/api/rate.py
  uiflow/components/heading.py
  uiflow/components/input.py
  uiflow/components/layout.py
  uiflow/components/yourTimelog.py
Labels: enhancement

#332 ✨ clickable dropdown arrows
  appflow/static/css/styles.css
Labels: enhancement

#331 ✨ Style change for disabled and active (on click) button
  appflow/static/css/styles.css
  uiflow/components/controls.py
Labels: enhancement

#333 #330 Add deactivate and activate option to missing tabs (Users, Roles, Epics)
  applications/timeflow/data/common.py
  applications/timeflow/data/epics.py
  applications/timeflow/data/roles.py
  applications/timeflow/data/teams.py
  applications/timeflow/data/users.py
  applications/timeflow/pages/roles.py
  applications/timeflow/pages/users.py
  backend/api/epic.py
  backend/api/role.py
  backend/api/user.py
Labels: enhancement

#335 #334 Add deactivate and activate option to Teams tab
  applications/timeflow/data/teams.py
  applications/timeflow/pages/teams.py
  backend/api/team.py
Labels: enhancement

#337 ✨ Added validator not to delete other users timelogs
  applications/timeflow/pages/timelogs.py
  backend/api/timelog.py
Labels: enhancement

#339 #338 Add deactivate and activate option to Sponsors tab
  applications/timeflow/data/sponsors.py
  applications/timeflow/pages/sponsors.py
  backend/api/sponsor.py
Labels: enhancement

#341 #340 Add deactivate and activate option to Clients tab
  applications/timeflow/data/clients.py
  applications/timeflow/pages/clients.py
  applications/timeflow/pages/sponsors.py
  backend/api/client.py
Labels: enhancement

#343 ✨ Fetch timelogs on-enter table by current month
  applications/timeflow/data/timelogs.py
  applications/timeflow/pages/timelogs.py
  backend/api/timelog.py
Labels: enhancement

#345 #344 Add deactivate and activate option to Epic Areas tab
  applications/timeflow/data/epic_areas.py
  applications/timeflow/pages/epic_areas.py
  backend/api/epic_area.py
Labels: enhancement

#347 [QuickFix] modified timelogs table with search & bug
  applications/timeflow/index.py
  applications/timeflow/pages/timelogs.py
  backend/api/user.py
Labels: bug, enhancement

#356 🐛 |Pages||Timelogs| inactive epic areas in dropdown
  applications/timeflow/data/epic_areas.py
  backend/api/epic_area.py
Labels: bug

#359 Fix cloud upload issue
  backup/backup_db.py
Labels: bug

#361 ✨ Order dropdowns alphabetically
  applications/timeflow/data/epic_areas.py
  backend/api/epic.py
  backend/api/epic_area.py
  backend/api/user.py
Labels: enhancement
