Repository dyvenia/timeflow, pull requests merged in 2022-03, with the labels that each got.

#113 Create admin epic areas page
  backend/api/epic_area.py
  backend/main.py
  backend/models/epic_area.py
  backend/tests/test_epic_area_api.py
  backend/utils.py
  frontend/components/sidebar.py
  frontend/index.py
  frontend/pages/epic_areas.py
  frontend/tailwind/package-lock.json
  frontend/tailwind/package.json
  frontend/tailwind/site/epic_areas.html
Labels: enhancement

#117 Create admin rates page
  backend/api/rate.py
  backend/models/rate.py
  backend/tests/test_rate_api.py
  backend/utils.py
  frontend/components/sidebar.py
  frontend/index.py
  frontend/pages/data.py
  frontend/pages/rates.py
  frontend/pages/utils.py
Labels: enhancement

#132 Move the comments in the APIs into docstrings so they will show up in the mkdocs API documentation
  backend/api/client.py
  backend/api/epic.py
  backend/api/epic_area.py
  backend/api/forecast.py
  backend/api/rate.py
  backend/api/sponsor.py
  backend/api/team.py
  backend/api/timelog.py
  backend/api/user.py
Labels: documentation

#135 Highlight sidebar button
  frontend/components/sidebar.py
Labels: enhancement

#133 Create [data] folder for storing common data
  frontend/components/input.py
  frontend/data/clients.py
  frontend/data/common.py
  frontend/data/epic_areas.py
  frontend/data/epics.py
  frontend/data/forecasts.py
  frontend/data/rates.py
  frontend/data/sponsors.py
  frontend/data/teams.py
  frontend/data/timelogs.py
  frontend/data/users.py
  frontend/data/utils.py
  frontend/pages/data.py
  frontend/pages/forecasts.py
  frontend/pages/rates.py
  frontend/pages/timelogs.py
Labels: enhancement

#143 Roles page
  backend/api/role.py
  backend/main.py
  backend/models/role.py
  backend/tests/test_role_api.py
  frontend/components/sidebar.py
  frontend/data/roles.py
  frontend/index.py
  frontend/pages/roles.py
Labels: enhancement

#145 Refactor epic_areas, teams, and sponsors into their respective data files
  frontend/data/clients.py
  frontend/data/common.py
  frontend/data/epic_areas.py
  frontend/data/epics.py
  frontend/data/sponsors.py
  frontend/data/teams.py
  frontend/data/users.py
  frontend/pages/epic_areas.py
  frontend/pages/sponsors.py
  frontend/pages/teams.py
Labels: code optimization

#154 Restructure epic areas, sponsors, and teams pages and their respective data files.
  backend/tests/sample.sql
  frontend/components/controls.py
  frontend/data/clients.py
  frontend/data/common.py
  frontend/data/epics.py
  frontend/data/users.py
  frontend/pages/epic_areas.py
  frontend/pages/sponsors.py
  frontend/pages/teams.py
Labels: code optimization

#152 Quick fix: Edit SQL test data to fit with updated epic model
  backend/tests/sample.sql
Labels: bug

#156 Users update
  backend/api/team.py
  backend/api/user.py
  backend/models/user.py
  backend/tests/sample.sql
  backend/tests/test_user_api.py
  frontend/data/common.py
  frontend/data/roles.py
  frontend/data/teams.py
  frontend/data/users.py
  frontend/pages/users.py
  frontend/pages/utils.py
Labels: enhancement

#162 Capacities page
  backend/api/capacity.py
  backend/main.py
  backend/models/capacity.py
  backend/tests/sample.sql
  backend/tests/test_capacity_api.py
  frontend/components/sidebar.py
  frontend/data/capacities.py
  frontend/data/teams.py
  frontend/index.py
  frontend/pages/capacities.py
  frontend/pages/users.py
  frontend/pages/utils.py
Labels: enhancement

#167 Handle SimpleTable error
  frontend/components/table.py
Labels: enhancement

#168 Team model change
  backend/api/team.py
  backend/models/team.py
  backend/tests/sample.sql
  backend/tests/test_team_api.py
  frontend/data/teams.py
  frontend/pages/teams.py
Labels: enhancement

#170 Update IDOM and fix import bug
  frontend/components/sidebar.py
  frontend/index.py
  requirements.txt
Labels: bug

#173 modified pagination
  frontend/components/input.py
  frontend/components/pagination.py
  frontend/components/table.py
  package-lock.json
Labels: enhancement
