Repository dyvenia/timeflow, pull requests merged in 2022-06, with the labels that each got.

#362 ✨ Notification of post timelog
  appflow/static/css/styles.css
  applications/timeflow/data/timelogs.py
  applications/timeflow/pages/timelogs.py
  backend/api/timelog.py
  uiflow/components/heading.py
  uiflow/components/input.py
Labels: enhancement

#363 Create migration scripts
  alembic.ini
  migrations/README
  migrations/env.py
  migrations/script.py.mako
Labels: enhancement

#368 #353 |Pages||Epic Areas| Update option
  applications/timeflow/data/epic_areas.py
  applications/timeflow/pages/epic_areas.py
  backend/api/epic_area.py
Labels: enhancement

#379 |Pages||Rates| Update usernames with full name
  applications/timeflow/data/rates.py
  applications/timeflow/pages/rates.py
  backend/api/rate.py
Labels: enhancement

#373 |Pages||Timelogs| Update usernames with full name
  applications/timeflow/data/common.py
  applications/timeflow/data/timelogs.py
  applications/timeflow/pages/forecasts.py
  applications/timeflow/pages/rates.py
  applications/timeflow/pages/timelogs.py
  backend/api/timelog.py
Labels: enhancement

#377 #376 |Pages||Users| not all fields entered needed to update a record
  applications/timeflow/data/users.py
  applications/timeflow/pages/users.py
Labels: bug

#378 |Pages||Teams| Update usernames with full name
  applications/timeflow/data/teams.py
  applications/timeflow/data/users.py
  applications/timeflow/pages/teams.py
  backend/api/team.py
  backend/api/user.py
Labels: enhancement

#381 Quick fix of SelectPerPage component
  uiflow/components/input.py
  uiflow/components/pagination.py
  uiflow/components/table.py
Labels: bug

#382 ✨ Remove forecast filter by user-epic-date
  applications/timeflow/data/forecasts.py
  applications/timeflow/pages/forecasts.py
  backend/api/forecast.py
Labels: enhancement

#380 |Pages||Capacities| Update usernames with full name
  applications/timeflow/data/capacities.py
  backend/api/capacity.py
Labels: enhancement

#389 |API|EpicArea| new start_date column in EpicArea model
  backend/models/epic_area.py
  migrations/versions/b85bfd91b12d_add_start_date_column_to_epicarea_model.py
Labels: enhancement, migration needed

#394 |Tests| Enhance sample.sql file with more test data
  backend/tests/sample.sql
Labels: enhancement
