Repository dyvenia/timeflow, pull requests merged in 2022-04, with the labels that each got.

#174 Add mkdocs documentation
  .gitignore
  README.md
  backend/api/capacity.py
  backend/api/client.py
  backend/api/demand.py
  backend/api/epic.py
  backend/api/epic_area.py
  backend/api/forecast.py
  backend/api/rate.py
  backend/api/role.py
  backend/api/sponsor.py
  backend/api/team.py
  backend/api/timelog.py
  backend/api/user.py
  backend/docs/model_specs.md
  docker-compose.yaml
  docs/api-reference.md
  docs/how-tos.md
  docs/index.md
  docs/tutorials.md
  mkdocs.yml
  model_specs.md
  requirements.txt
Labels: documentation

#175 Dev
  backend/api/epic_area.py
  frontend/components/controls.py
  frontend/components/header.py
  frontend/components/heading.py
  frontend/components/icons.py
  frontend/components/input.py
  frontend/components/layout.py
  frontend/components/pagination.py
  frontend/components/sidebar.py
  frontend/components/table.py
  frontend/components/tablebatch_row.py
  frontend/components/yourTimelog.py
  frontend/css/custom.css
  frontend/css/styles.css
  frontend/css/tailwind.css
  frontend/fonts/Mulish-Black.ttf
  frontend/fonts/Mulish-Regular.ttf
  frontend/fonts/Mulish-VariableFont_wght.ttf
  frontend/img/.DS_Store
  frontend/img/.meta/favicon.ico.yaml
  frontend/img/svg/.DS_Store
  frontend/img/svg/Burger.svg
  frontend/img/svg/arrow.svg
  frontend/img/svg/batchActions.svg
  frontend/img/svg/cross.svg
  frontend/img/svg/delete.svg
  frontend/img/svg/done.svg
  frontend/img/svg/edit.svg
  frontend/img/svg/filter.svg
  frontend/img/svg/logo.svg
  frontend/img/svg/search.svg
  frontend/index.py
  frontend/pages/capacities.py
  frontend/pages/demands.py
  frontend/pages/epic_areas.py
  frontend/pages/epics.py
  frontend/pages/forecasts.py
  frontend/pages/rates.py
  frontend/pages/roles.py
  frontend/pages/sponsors.py
  frontend/pages/teams.py
  frontend/pages/timelogs.py
  frontend/pages/users.py
  frontend/run_app.py
  package-lock.json
Labels: enhancement

#189 Configure app for latest idom release
  frontend/components/sidebar.py
  frontend/pages/clients.py
  frontend/pages/users.py
  frontend/run_app.py
  frontend/tailwind/package-lock.json
  frontend/tailwind/package.json
  requirements.txt
Labels: enhancement

#191 [Quick Fix] Serve static files
  frontend/pages/users.py
  frontend/run_app.py
Labels: bug

#194 Create user authentication utilizing basic auth
  frontend/components/sidebar.py
  frontend/config.py
  frontend/index.py
Labels: enhancement

#206 User table mod
  backend/api/user.py
  backend/models/user.py
  frontend/data/users.py
Labels: enhancement

#214 Updated forecasts validator
  backend/api/forecast.py
Labels: bug

#215 GitHub authentication | IDOM embedding | docker-compose-dev
  .gitignore
  backend/main.py
  docker-compose-dev.yaml
  docker-compose.yaml
  frontend/components/sidebar.py
  frontend/config.py
  frontend/embedding_script.js
  frontend/index.py
  frontend/run_app.py
  frontend/run_reload.py
  requirements.txt
Labels: enhancement

#218 Add documentation for using TimeFlow in developer mode
  .gitignore
  .nojekyll
  404.html
  api-reference/index.html
  assets/_mkdocstrings.css
  assets/images/favicon.png
  assets/javascripts/bundle.c44cc438.min.js
  assets/javascripts/bundle.c44cc438.min.js.map
  assets/javascripts/lunr/min/lunr.ar.min.js
  assets/javascripts/lunr/min/lunr.da.min.js
  assets/javascripts/lunr/min/lunr.de.min.js
  assets/javascripts/lunr/min/lunr.du.min.js
  assets/javascripts/lunr/min/lunr.es.min.js
  assets/javascripts/lunr/min/lunr.fi.min.js
  assets/javascripts/lunr/min/lunr.fr.min.js
  assets/javascripts/lunr/min/lunr.hi.min.js
  assets/javascripts/lunr/min/lunr.hu.min.js
  assets/javascripts/lunr/min/lunr.it.min.js
  assets/javascripts/lunr/min/lunr.ja.min.js
  assets/javascripts/lunr/min/lunr.jp.min.js
  assets/javascripts/lunr/min/lunr.multi.min.js
  assets/javascripts/lunr/min/lunr.nl.min.js
  assets/javascripts/lunr/min/lunr.no.min.js
  assets/javascripts/lunr/min/lunr.pt.min.js
  assets/javascripts/lunr/min/lunr.ro.min.js
  assets/javascripts/lunr/min/lunr.ru.min.js
  assets/javascripts/lunr/min/lunr.stemmer.support.min.js
  assets/javascripts/lunr/min/lunr.sv.min.js
  assets/javascripts/lunr/min/lunr.th.min.js
  assets/javascripts/lunr/min/lunr.tr.min.js
  assets/javascripts/lunr/min/lunr.vi.min.js
  assets/javascripts/lunr/min/lunr.zh.min.js
  assets/javascripts/lunr/tinyseg.js
  assets/javascripts/lunr/wordcut.js
  assets/javascripts/workers/search.5e67fbfe.min.js
  assets/javascripts/workers/search.5e67fbfe.min.js.map
  assets/stylesheets/main.644de097.min.css
  assets/stylesheets/main.644de097.min.css.map
  assets/stylesheets/palette.e6a45f82.min.css
  assets/stylesheets/palette.e6a45f82.min.css.map
  how-tos/index.html
  index.html
  objects.inv
  search/search_index.json
  sitemap.xml
  sitemap.xml.gz
  tutorials/index.html
Labels: documentation

#219 Add documentation for using TimeFlow in developer mode
  docs/how-tos.md
  docs/index.md
Labels: documentation

#222 Add new dev permissions
  frontend/run_app.py
Labels: documentation

#223 Add updated documentation
  api-reference/index.html
  how-tos/index.html
  index.html
  objects.inv
  search/search_index.json
  sitemap.xml
  sitemap.xml.gz
Labels: documentation

#224 Add documentation link to readme
  README.md
Labels: documentation

#226 [Quickfix] Configure https when not in dev mode
  frontend/run_app.py
Labels: bug

#227 Add user welcoming
  frontend/components/header.py
  frontend/components/sidebar.py
  frontend/config.py
  frontend/index.py
  frontend/run_app.py
Labels: bug

#234 Configure components to allow for roles
  build.sh
  docker-compose-dev.yaml
  uiflow/components/header.py
  uiflow/components/sidebar.py
Labels: bug

#238 Migrate database to PostgreSQL
  backend/api/capacity.py
  backend/api/demand.py
  backend/api/team.py
  backend/api/timelog.py
  backend/api/user.py
  backend/main.py
  backend/models/calendar.py
  backend/models/capacity.py
  backend/models/client.py
  backend/models/demand.py
  backend/models/epic.py
  backend/models/epic_area.py
  backend/models/forecast.py
  backend/models/rate.py
  backend/models/role.py
  backend/models/sponsor.py
  backend/models/team.py
  backend/models/timelog.py
  backend/models/user.py
  backend/tests/sample.sql
  backend/utils.py
  docker-compose-dev.yaml
  main.py
  requirements.txt
Labels: enhancement

#239 Pytest order
  backend/api/client.py
  backend/api/epic_area.py
  backend/api/forecast.py
  backend/api/rate.py
  backend/api/sponsor.py
  backend/api/team.py
  backend/api/timelog.py
  backend/main.py
  backend/tests/test_capacity_api.py
  backend/tests/test_client_api.py
  backend/tests/test_demand_api.py
  backend/tests/test_epic_api.py
  backend/tests/test_epic_area_api.py
  backend/tests/test_forecast_api.py
  backend/tests/test_rate_api.py
  backend/tests/test_role_api.py
  backend/tests/test_sponsor_api.py
  backend/tests/test_team_api.py
  backend/tests/test_timelog_api.py
  backend/tests/test_user_api.py
Labels: enhancement

#241 [Quickfix] Close connections and increase pool size of engine
  backend/main.py
  backend/models/user.py
  backend/utils.py
Labels: bug

#244 Rework user page, automatically post users to database
  appflow/views/login_github.py
  applications/timeflow/data/capacities.py
  applications/timeflow/data/common.py
  applications/timeflow/data/epics.py
  applications/timeflow/data/roles.py
  applications/timeflow/data/teams.py
  applications/timeflow/data/timelogs.py
  applications/timeflow/data/users.py
  applications/timeflow/index.py
  applications/timeflow/pages/capacities.py
  applications/timeflow/pages/clients.py
  applications/timeflow/pages/demands.py
  applications/timeflow/pages/epic_areas.py
  applications/timeflow/pages/epics.py
  applications/timeflow/pages/forecasts.py
  applications/timeflow/pages/rates.py
  applications/timeflow/pages/roles.py
  applications/timeflow/pages/sponsors.py
  applications/timeflow/pages/teams.py
  applications/timeflow/pages/timelogs.py
  applications/timeflow/pages/users.py
  applications/timeflow/pages/utils.py
  backend/api/capacity.py
  backend/api/client.py
  backend/api/demand.py
  backend/api/epic.py
  backend/api/epic_area.py
  backend/api/forecast.py
  backend/api/rate.py
  backend/api/role.py
  backend/api/team.py
  backend/api/timelog.py
  backend/api/user.py
  backend/main.py
  backend/models/calendar.py
  backend/models/capacity.py
  backend/models/client.py
  backend/models/demand.py
  backend/models/epic.py
  backend/models/epic_area.py
  backend/models/forecast.py
  backend/models/rate.py
  backend/models/role.py
  backend/models/sponsor.py
  backend/models/team.py
  backend/models/timelog.py
  backend/models/user.py
  backend/tests/sample.sql
  backend/tests/test_user_api.py
Labels: enhancement

#246 Configure docker-compose deploy script to work with postgres | Rework user page, automatically post users to database | Migrate database to PostgreSQL |
  appflow/views/login_github.py
  backend/main.py
  backend/utils.py
  docker-compose-dev.yaml
  docker-compose.yaml
  main.py
Labels: enhancement

#248 [Quick Fix] Increase pool size
  backend/utils.py
Labels: bug, enhancement

#251 [Quick Fix] cleaning unused sessions
  backend/main.py
  backend/utils.py
  docker-compose-dev.yaml
Labels: enhancement

#253 [Quick Fix] Missing session dependency
  backend/api/epic.py
Labels: enhancement

#255 [Clients page] added activation/deactivation feature
  applications/timeflow/data/clients.py
  applications/timeflow/data/sponsors.py
  applications/timeflow/pages/clients.py
  applications/timeflow/pages/epics.py
  backend/api/client.py
  backend/tests/test_client_api.py
Labels: enhancement

#257 [Quick Fix] Remove user validator
  backend/models/user.py
Labels: bug
